groups_index:
    path:     /
    defaults: { _controller: "FKSCentralBundle:Groups:index" }
    methods:  GET

groups_show:
    path:     /{id}/show
    defaults: { _controller: "FKSCentralBundle:Groups:show" }
    methods:  GET

groups_new:
    path:     /new
    defaults: { _controller: "FKSCentralBundle:Groups:new" }
    methods:  [GET, POST]

groups_edit:
    path:     /{id}/edit
    defaults: { _controller: "FKSCentralBundle:Groups:edit" }
    methods:  [GET, POST]

groups_delete:
    path:     /{id}/delete
    defaults: { _controller: "FKSCentralBundle:Groups:delete" }
    methods:  DELETE
