<?php

namespace Fokkus\V1Bundle\Repository;

/**
 * sousstepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sousstepRepository extends \Doctrine\ORM\EntityRepository
{
}
