<?php

namespace Fokkus\V1Bundle\Repository;

/**
 * stepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stepRepository extends \Doctrine\ORM\EntityRepository
{
}
