<?php

namespace Fokkus\V1Bundle\Repository;

/**
 * scoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class scoresRepository extends \Doctrine\ORM\EntityRepository
{
}
