<?php

namespace FKS\CentralBundle\Repository;

/**
 * ContactUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactUserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getContactUser($receiverId, $senderId)
    {


        $qb = $this->createQueryBuilder('n');
        $qb->select('n')
            ->where('n.sender = :sender')
            ->andWhere('n.receiver = :receiver')
            ->setParameter('sender', $senderId)
            ->setParameter('receiver', $receiverId)
        ;
//dump($qb->getQuery()->getResult());die;
        return $qb->getQuery()->getResult();
    }
}
