<?php

namespace FKS\CentralBundle\Repository;

/**
 * PartenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenerRepository extends \Doctrine\ORM\EntityRepository
{

    public function getPartenerkByGroup($group)
    {

        $qb = $this->createQueryBuilder('c');
        $qb->select('c')
            //->leftJoin('c.network', 'j')
            ->where('c.group = :group') //to do
            ->setParameter('group', $group);

        return $qb->getQuery()->getResult();

    }
}
