<?php

namespace FKS\CentralBundle\Repository;

/**
 * PartenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenerRepository extends \Doctrine\ORM\EntityRepository
{
}
