<?php

namespace FKS\CentralBundle\Repository;

/**
 * RequestContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestContactRepository extends \Doctrine\ORM\EntityRepository
{
}
