<?php

namespace FKS\CentralBundle\Repository;

/**
 * StartupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StartupRepository extends \Doctrine\ORM\EntityRepository
{
}
