<?php

namespace FKS\CentralBundle\Repository;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueRepository extends \Doctrine\ORM\EntityRepository
{

    public function getStatistiqueByGroup($group)
    {

        $qb = $this->createQueryBuilder('c');
        $qb->select('c')
            ->leftJoin('c.sub', 'j')
            ->leftJoin('j.network', 'n')
            ->where('n.group = :group') //to do jurist
            ->setParameter('group', $group);

        return $qb->getQuery()->getResult();

    }
}
