<?php

namespace FKS\CentralBundle\Repository;

/**
 * subPartenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class subPartenerRepository extends \Doctrine\ORM\EntityRepository
{

    public function getSubPartenerByGroup($group)
    {

        $qb = $this->createQueryBuilder('c');
        $qb->select('c')
            ->leftJoin('c.partener', 'j')
            ->where('j.group = :group') //to do jurist
            ->setParameter('group', $group);

        return $qb->getQuery()->getResult();

    }

}
