<?php

namespace FKS\CentralBundle\Repository;

/**
 * subPartenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class subPartenerRepository extends \Doctrine\ORM\EntityRepository
{
}
