formationcateg_index:
    path:     /
    defaults: { _controller: "FokkusV1Bundle:formationcateg:index" }
    methods:  GET

formationcateg_show:
    path:     /{id}/show
    defaults: { _controller: "FokkusV1Bundle:formationcateg:show" }
    methods:  GET

formationcateg_new:
    path:     /new
    defaults: { _controller: "FokkusV1Bundle:formationcateg:new" }
    methods:  [GET, POST]

formationcateg_edit:
    path:     /{id}/edit
    defaults: { _controller: "FokkusV1Bundle:formationcateg:edit" }
    methods:  [GET, POST]

formationcateg_delete:
    path:     /{id}/delete
    defaults: { _controller: "FokkusV1Bundle:formationcateg:delete" }
    methods:  DELETE
