groupe_index:
    path:     /
    defaults: { _controller: "FokkusV1Bundle:groupe:index" }
    methods:  GET

groupe_show:
    path:     /{id}/show
    defaults: { _controller: "FokkusV1Bundle:groupe:show" }
    methods:  GET

groupe_new:
    path:     /new
    defaults: { _controller: "FokkusV1Bundle:groupe:new" }
    methods:  [GET, POST]

groupe_edit:
    path:     /{id}/edit
    defaults: { _controller: "FokkusV1Bundle:groupe:edit" }
    methods:  [GET, POST]

groupe_delete:
    path:     /{id}/delete
    defaults: { _controller: "FokkusV1Bundle:groupe:delete" }
    methods:  DELETE
