step_index:
    path:     /index/{type}/{group}/
    defaults: { _controller: "FokkusV1Bundle:step:index" }
    methods:  GET
stepsgroups:
    path:     /stepsgroups/{type}
    defaults: { _controller: "FokkusV1Bundle:step:stepsgroups" }
    methods:  GET    
step_visualtion:
    path:     /step_visualtion
    defaults: { _controller: "FokkusV1Bundle:step:step_visualtion" }
step_show:
    path:     /{id}/show
    defaults: { _controller: "FokkusV1Bundle:step:show" }
    methods:  GET

step_new:
    path:     /step_new
    defaults: { _controller: "FokkusV1Bundle:step:new" }
    methods:  [GET, POST]

step_edit:
    path:     /{id}/edit
    defaults: { _controller: "FokkusV1Bundle:step:edit" }
    methods:  [GET, POST]

step_delete:
    path:     /{id}/delete
    defaults: { _controller: "FokkusV1Bundle:step:delete" }
    methods:  DELETE
